<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class WP_FixPilot_Error_Monitor {
	private static $instance=null; private $previous_handler=null;
	public static function instance(){ if(null===self::$instance)self::$instance=new self(); return self::$instance; }
	public static function install_table(){ global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $table=$wpdb->prefix.'fixpilot_issues'; $charset=$wpdb->get_charset_collate(); dbDelta("CREATE TABLE {$table} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,fingerprint char(40) NOT NULL,severity varchar(30) NOT NULL,message text NOT NULL,file text NULL,line int(11) unsigned NOT NULL DEFAULT 0,source varchar(191) NULL,first_seen datetime NOT NULL,last_seen datetime NOT NULL,occurrences bigint(20) unsigned NOT NULL DEFAULT 1,PRIMARY KEY (id),UNIQUE KEY fingerprint (fingerprint),KEY severity (severity),KEY last_seen (last_seen)) {$charset};"); }
	public function init(){ $s=get_option('wp_fixpilot_settings',array()); if(empty($s['monitor_errors']))return; $this->previous_handler=set_error_handler(array($this,'handle_error'),E_WARNING|E_USER_WARNING|E_NOTICE|E_USER_NOTICE|E_DEPRECATED|E_USER_DEPRECATED); register_shutdown_function(array($this,'handle_shutdown')); }
	public function handle_error($errno,$errstr,$errfile,$errline){ if(!(error_reporting()&$errno))return false; self::record($this->severity_name($errno),$errstr,$errfile,$errline); if(is_callable($this->previous_handler))return (bool)call_user_func($this->previous_handler,$errno,$errstr,$errfile,$errline); return false; }
	public function handle_shutdown(){ $e=error_get_last(); if(!$e||!in_array($e['type'],array(E_ERROR,E_PARSE,E_CORE_ERROR,E_COMPILE_ERROR,E_USER_ERROR),true))return; self::record('Fatal',$e['message'],$e['file'],$e['line']); }
	private static function record($severity,$message,$file,$line){ global $wpdb; $table=$wpdb->prefix.'fixpilot_issues'; $source=self::detect_source($file); $fingerprint=sha1($severity.'|'.$message.'|'.$file.'|'.(int)$line); $now=current_time('mysql',true); $existing=$wpdb->get_var($wpdb->prepare("SELECT id FROM {$table} WHERE fingerprint=%s",$fingerprint)); if($existing){$wpdb->query($wpdb->prepare("UPDATE {$table} SET last_seen=%s,occurrences=occurrences+1 WHERE id=%d",$now,$existing));return;} $wpdb->insert($table,array('fingerprint'=>$fingerprint,'severity'=>$severity,'message'=>wp_strip_all_tags($message),'file'=>wp_normalize_path($file),'line'=>(int)$line,'source'=>$source,'first_seen'=>$now,'last_seen'=>$now,'occurrences'=>1),array('%s','%s','%s','%s','%d','%s','%s','%s','%d')); }
	private function severity_name($errno){$m=array(E_WARNING=>'Warning',E_USER_WARNING=>'User Warning',E_NOTICE=>'Notice',E_USER_NOTICE=>'User Notice',E_DEPRECATED=>'Deprecated',E_USER_DEPRECATED=>'User Deprecated');return isset($m[$errno])?$m[$errno]:'Unknown';}
	private static function detect_source($file){$file=wp_normalize_path($file);$plugins=wp_normalize_path(WP_PLUGIN_DIR).'/';$themes=wp_normalize_path(get_theme_root()).'/';if(0===strpos($file,$plugins)){return 'plugin:'.strtok(substr($file,strlen($plugins)),'/');}if(0===strpos($file,$themes)){return 'theme:'.strtok(substr($file,strlen($themes)),'/');}if(0===strpos($file,wp_normalize_path(ABSPATH)))return 'wordpress-core';return 'server-or-custom';}
	public static function recent_issues($limit=100){global $wpdb;$table=$wpdb->prefix.'fixpilot_issues';$limit=max(1,min(500,(int)$limit));return $wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} ORDER BY FIELD(severity,'Fatal','Warning','User Warning','Deprecated','User Deprecated','Notice','User Notice'),last_seen DESC LIMIT %d",$limit),ARRAY_A);}
	public static function clear(){global $wpdb;$table=$wpdb->prefix.'fixpilot_issues';return false!==$wpdb->query("TRUNCATE TABLE {$table}");}
}
