<?php
if(!defined('ABSPATH'))exit;
class WP_FixPilot_Update_Guard_Pro {
 public static function init(){add_filter('upgrader_pre_install',array(__CLASS__,'pre'),8,2);add_action('upgrader_process_complete',array(__CLASS__,'post'),20,2);}
 private static function root(){ $u=wp_upload_dir();$d=trailingslashit($u['basedir']).'wp-fixpilot/update-guard';if(!is_dir($d))wp_mkdir_p($d);return $d; }
 public static function pre($response,$extra){$type=isset($extra['type'])?$extra['type']:'';$item='';if('plugin'===$type&&!empty($extra['plugin']))$item=$extra['plugin'];elseif('theme'===$type&&!empty($extra['theme']))$item=$extra['theme'];elseif('core'===$type)$item='wordpress-core';if(!$item)return $response;$src='';if('plugin'===$type)$src=trailingslashit(WP_PLUGIN_DIR).dirname($item);elseif('theme'===$type)$src=trailingslashit(get_theme_root()).$item;if($src&&!is_dir($src)&&is_file($src))$src=dirname($src);$id=gmdate('Ymd-His').'-'.wp_generate_password(6,false,false);$dst=$src?trailingslashit(self::root()).$id:'';$copy=$src?self::copy_tree($src,$dst):true;$manifest=array('id'=>$id,'type'=>$type,'item'=>$item,'source'=>wp_normalize_path($src),'backup'=>wp_normalize_path($dst),'time'=>time(),'ok'=>$copy,'baseline'=>WP_FixPilot_Benchmark::run());update_option('wp_fixpilot_update_guard_pro_pending',$manifest,false);return $response;}
 public static function post($upgrader,$extra){$m=(array)get_option('wp_fixpilot_update_guard_pro_pending',array());if(!$m)return;$after=WP_FixPilot_Benchmark::run();$bad=false;foreach($after as $k=>$r)if(is_array($r)&&isset($r['code'])&&(int)$r['code']>=500)$bad=true;$b=isset($m['baseline']['home']['ms'])?(float)$m['baseline']['home']['ms']:0;$a=isset($after['home']['ms'])?(float)$after['home']['ms']:0;if($b&&$a>$b*1.7&&$a-$b>500)$bad=true;$m['after']=$after;$m['status']=$bad?'regression':'pass';$m['completed']=time();$h=(array)get_option('wp_fixpilot_update_guard_pro_history',array());array_unshift($h,$m);update_option('wp_fixpilot_update_guard_pro_history',array_slice($h,0,20),false);delete_option('wp_fixpilot_update_guard_pro_pending');if($bad&&apply_filters('wp_fixpilot_auto_rollback_bad_update',false,$m))self::rollback($m['id']);}
 public static function rollback($id){$h=(array)get_option('wp_fixpilot_update_guard_pro_history',array());foreach($h as &$m){if($m['id']!==$id)continue;if(empty($m['backup'])||empty($m['source'])||!is_dir($m['backup']))return new WP_Error('fixpilot_update_backup_missing','Update backup is unavailable.');$safe=0===strpos(wp_normalize_path($m['source']),wp_normalize_path(WP_PLUGIN_DIR).'/')||0===strpos(wp_normalize_path($m['source']),wp_normalize_path(get_theme_root()).'/');if(!$safe)return new WP_Error('fixpilot_update_path','Unsafe rollback path.');self::delete_tree($m['source']);if(!self::copy_tree($m['backup'],$m['source']))return new WP_Error('fixpilot_update_restore','Could not restore update backup.');$m['status']='rolled_back';$m['rolled_back']=time();update_option('wp_fixpilot_update_guard_pro_history',$h,false);return true;}return new WP_Error('fixpilot_update_record','Update record not found.');}
 private static function copy_tree($src,$dst){if(!is_dir($src))return false;if(!is_dir($dst)&&!wp_mkdir_p($dst))return false;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($src,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::SELF_FIRST);foreach($it as $f){$to=$dst.DIRECTORY_SEPARATOR.$it->getSubPathName();if($f->isDir()){if(!is_dir($to)&&!mkdir($to,0755,true))return false;}elseif(!copy($f->getPathname(),$to))return false;}return true;}
 private static function delete_tree($p){if(!is_dir($p))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($p,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){$f->isDir()?rmdir($f->getPathname()):unlink($f->getPathname());}@rmdir($p);}
 public static function history(){return (array)get_option('wp_fixpilot_update_guard_pro_history',array());}
}
