<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class WP_FixPilot_Admin {
    private static $instance = null;
    public static function instance(){ if(null===self::$instance) self::$instance=new self(); return self::$instance; }
    public function init(){
        add_action('admin_menu',array($this,'menu')); add_action('admin_enqueue_scripts',array($this,'assets')); add_action('admin_notices',array($this,'safe_mode_notice'));
        foreach(array('scan','fix','clear_log','export','save_settings','repair_issue','benchmark','safe_mode_start','safe_mode_stop','conflict_profile','restore_backup','update_guard_compare','request_profile','safe_repair_all','auto_repair','repair_autoload','restore_autoload','restore_config','install_recovery_bridge','quarantine_plugin','restore_quarantined_plugin','rollback_update','save_ai_settings','ai_propose','ai_apply') as $a){ add_action('admin_post_wp_fixpilot_'.$a,array($this,$a)); }
        add_filter('plugin_action_links_'.plugin_basename(WP_FIXPILOT_FILE),array($this,'plugin_action_links'));
    }
    public function menu(){
        add_menu_page('WP FixPilot','WP FixPilot','manage_options','wp-fixpilot',array($this,'dashboard'),'dashicons-shield-alt',58);
        $items=array('wp-fixpilot'=>array('Dashboard','dashboard'),'wp-fixpilot-actions'=>array('Action Center','action_center'),'wp-fixpilot-issues'=>array('PHP Issues','issues'),'wp-fixpilot-plugins'=>array('Plugins','plugins'),'wp-fixpilot-performance'=>array('Performance','performance'),'wp-fixpilot-profiler'=>array('Request Profiler','profiler'),'wp-fixpilot-database'=>array('Database','database'),'wp-fixpilot-woocommerce'=>array('WooCommerce','woocommerce'),'wp-fixpilot-auto-repair'=>array('Auto Repair','auto_repair_page'),'wp-fixpilot-repairs'=>array('Repairs','repairs'),'wp-fixpilot-safety'=>array('Production Safety','safety_page'),'wp-fixpilot-rules'=>array('Repair Rules','repair_rules_page'),'wp-fixpilot-performance-repair'=>array('Performance Repair','performance_repair_page'),'wp-fixpilot-conflicts'=>array('Conflict Resolution','conflict_resolution_page'),'wp-fixpilot-update-guard-pro'=>array('Update Guard Pro','update_guard_pro_page'),'wp-fixpilot-ai'=>array('AI Repair','ai_repair_page'),'wp-fixpilot-release'=>array('Release Readiness','release_readiness_page'),'wp-fixpilot-settings'=>array('Settings','settings_page'));
        foreach($items as $slug=>$m) add_submenu_page('wp-fixpilot','WP FixPilot — '.$m[0],$m[0],'manage_options',$slug,array($this,$m[1]));
    }
    public function assets($hook){ wp_enqueue_style('wp-fixpilot-menu',WP_FIXPILOT_URL.'assets/admin-menu.css',array(),WP_FIXPILOT_VERSION); if(false!==strpos($hook,'wp-fixpilot')){ wp_enqueue_style('wp-fixpilot-admin',WP_FIXPILOT_URL.'assets/admin.css',array('wp-fixpilot-menu'),WP_FIXPILOT_VERSION); wp_enqueue_script('wp-fixpilot-metrics',WP_FIXPILOT_URL.'assets/admin-metrics.js',array(),WP_FIXPILOT_VERSION,true); } }
    public function plugin_action_links($links){ array_unshift($links,'<a href="'.esc_url(admin_url('admin.php?page=wp-fixpilot')).'">Dashboard</a>','<a href="'.esc_url(admin_url('admin.php?page=wp-fixpilot-settings')).'"><strong>Settings</strong></a>'); return $links; }
    private function auth($a){ if(!current_user_can('manage_options')) wp_die(esc_html__('Forbidden','wp-fixpilot')); check_admin_referer($a); }
    private function go($page,$msg){ wp_safe_redirect(add_query_arg(array('page'=>$page,'msg'=>$msg),admin_url('admin.php'))); exit; }
    private function report(){ $r=get_option('wp_fixpilot_last_scan',array()); if(empty($r)){ $r=WP_FixPilot_Scanner::run_full_scan(); update_option('wp_fixpilot_last_scan',$r,false); } return $r; }
    private function start($title,$desc=''){ echo '<div class="wrap wp-fixpilot-wrap"><h1>'.esc_html($title).'</h1>'; if($desc) echo '<p>'.esc_html($desc).'</p>'; echo '<div class="wpfix-legend"><span class="wpfix-metric-badge wpfix-critical">Critical</span><span class="wpfix-metric-badge wpfix-danger">Danger</span><span class="wpfix-metric-badge wpfix-attention">Attention</span><span class="wpfix-metric-badge wpfix-safe">Safe</span></div>'; if(isset($_GET['msg'])) echo '<div class="notice notice-info"><p>'.esc_html(sanitize_text_field(wp_unslash($_GET['msg']))).'</p></div>'; }
    private function end(){ echo '</div>'; }
    private function post_button($label,$action,$fields=array(),$class='secondary'){ echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="display:inline-block;margin:0 6px 6px 0">'; wp_nonce_field('wp_fixpilot_'.$action); echo '<input type="hidden" name="action" value="wp_fixpilot_'.esc_attr($action).'">'; foreach($fields as $k=>$v) echo '<input type="hidden" name="'.esc_attr($k).'" value="'.esc_attr($v).'">'; submit_button($label,$class,'submit',false); echo '</form>'; }
    private function json($data){ echo '<pre style="white-space:pre-wrap;max-height:650px;overflow:auto;background:#fff;padding:14px;border:1px solid #ccd0d4">'.esc_html(wp_json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)).'</pre>'; }
    public function safe_mode_notice(){ if(WP_FixPilot_Safe_Mode::active()) echo '<div class="notice notice-warning"><p><strong>WP FixPilot Safe Mode is active for this browser only.</strong></p></div>'; }
    public function dashboard(){ $r=$this->report(); $this->start('WP FixPilot','Diagnostics → repair → validation → rollback.'); echo '<div class="wp-fixpilot-score"><strong>'.esc_html((int)$r['score']).'</strong><span>Site Health / 100</span></div>'; $this->post_button('Run Full Scan','scan',array(),'primary'); $this->post_button('Export JSON','export'); $a=WP_FixPilot_Action_Center::build($r,get_option('wp_fixpilot_request_profiles',array())); $this->json(array('action_center'=>$a['counts'],'performance'=>$r['performance'],'woocommerce'=>$r['woocommerce'])); $this->end(); }
    public function action_center(){ $this->start('Action Center'); $this->json(WP_FixPilot_Action_Center::build($this->report(),get_option('wp_fixpilot_request_profiles',array()))); $this->end(); }
    public function issues(){ $this->start('PHP Issues'); $this->post_button('Clear log','clear_log'); $this->json(WP_FixPilot_Error_Monitor::recent_issues(250)); $this->end(); }
    public function plugins(){ $this->start('Plugins'); $this->post_button('Run Conflict Profiler','conflict_profile'); if(WP_FixPilot_Safe_Mode::active()) $this->post_button('Stop Safe Mode','safe_mode_stop'); else $this->post_button('Start Safe Mode','safe_mode_start'); $this->json(WP_FixPilot_Plugin_Analyzer::analyze()); $this->end(); }
    public function performance(){ $this->start('Performance'); $this->post_button('Run Benchmark','benchmark'); $this->json(array('analysis'=>WP_FixPilot_Performance::analyze(),'benchmark'=>get_option('wp_fixpilot_last_benchmark',array()),'plan'=>WP_FixPilot_Optimization_Plan::build($this->report(),get_option('wp_fixpilot_request_profiles',array())))); $this->end(); }
    public function profiler(){ $this->start('Request Profiler'); $this->post_button('Run Request Profiler','request_profile',array(),'primary'); $this->json(get_option('wp_fixpilot_request_profiles',array())); $this->end(); }
    public function database(){ $this->start('Database'); $this->json(WP_FixPilot_Database::analyze()); $this->end(); }
    public function woocommerce(){ $this->start('WooCommerce'); $this->json(array('diagnostics'=>WP_FixPilot_WooCommerce::analyze(),'bottlenecks'=>WP_FixPilot_WooCommerce_Bottleneck::analyze(get_option('wp_fixpilot_request_profiles',array())))); $this->end(); }
    public function auto_repair_page(){ $this->start('Auto Repair','Applies only eligible repairs and validates after every step.'); $this->post_button('Run Auto Repair','auto_repair',array(),'primary'); $this->json(get_option('wp_fixpilot_auto_repair_last',array())); $this->end(); }
    public function repairs(){ $this->start('Repair Center'); $this->post_button('Safe Repair All','safe_repair_all',array(),'primary'); $items=WP_FixPilot_Repair_Center::candidates(); echo '<table class="widefat striped"><thead><tr><th>Repair</th><th>Confidence</th><th>Risk</th><th>Target</th><th>Action</th></tr></thead><tbody>'; foreach($items as $c){ echo '<tr><td>'.esc_html($c['label']).'<br><small>'.esc_html($c['detail']).'</small></td><td>'.esc_html($c['confidence']).'%</td><td>'.esc_html($c['risk']).'</td><td><code>'.esc_html($c['target']).'</code></td><td>'; if('code'===$c['kind']) $this->post_button('Repair','repair_issue',array('issue_id'=>$c['fields']['issue_id'])); elseif('repair_autoload'===$c['action']) $this->post_button('Apply','repair_autoload',array('option_name'=>$c['fields']['option_name'])); elseif('fix'===$c['action']) $this->post_button('Apply','fix',array('fix'=>$c['fields']['fix'])); echo '</td></tr>'; } echo '</tbody></table>'; $this->end(); }
    public function safety_page(){ $this->start('Production Safety'); $this->post_button('Install / repair recovery bridge','install_recovery_bridge'); $this->json(WP_FixPilot_Safety::preflight(false)); $this->end(); }
    public function repair_rules_page(){ $this->start('Repair Rules'); $this->json(array('rules'=>WP_FixPilot_Repair_Rule_Library::rules(),'detected'=>WP_FixPilot_Repair_Rule_Library::summary())); $this->end(); }
    public function performance_repair_page(){ $this->start('Performance Repair'); $this->json(WP_FixPilot_Performance_Repair::repair_plan()); $this->end(); }
    public function conflict_resolution_page(){ $this->start('Conflict Resolution'); $this->json(array('plans'=>WP_FixPilot_Conflict_Resolution::plans(),'quarantined'=>WP_FixPilot_Conflict_Resolution::quarantined())); $this->end(); }
    public function update_guard_pro_page(){ $this->start('Update Guard Pro'); $this->json(WP_FixPilot_Update_Guard_Pro::history()); $this->end(); }
    public function release_readiness_page(){ $this->start('Release Readiness'); $this->json(WP_FixPilot_Release_Readiness::checks()); $this->end(); }
    public function settings_page(){ $s=wp_parse_args((array)get_option('wp_fixpilot_settings',array()),array('monitor_errors'=>1,'weekly_scan'=>1,'auto_expired_cleanup'=>0,'allow_code_repairs'=>0,'backup_retention'=>30,'auto_repair_max_steps'=>8)); $this->start('Settings'); echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'; wp_nonce_field('wp_fixpilot_save_settings'); echo '<input type="hidden" name="action" value="wp_fixpilot_save_settings">'; foreach(array('monitor_errors'=>'Monitor PHP warnings/deprecations','weekly_scan'=>'Weekly scan','auto_expired_cleanup'=>'Clean expired transients before scheduled scan','allow_code_repairs'=>'Allow high-confidence code repairs') as $k=>$l) echo '<p><label><input type="checkbox" name="'.esc_attr($k).'" value="1" '.checked(1,$s[$k],false).'> '.esc_html($l).'</label></p>'; echo '<p><label>Backup retention days <input type="number" name="backup_retention" min="7" max="180" value="'.esc_attr($s['backup_retention']).'"></label></p><p><label>Auto Repair max steps <input type="number" name="auto_repair_max_steps" min="1" max="25" value="'.esc_attr($s['auto_repair_max_steps']).'"></label></p>'; submit_button('Save Settings'); echo '</form>'; $this->end(); }
    public function ai_repair_page(){ $cfg=WP_FixPilot_AI_Repair::settings(); $this->start('AI Repair Assistant','Opt-in only; proposals still pass through the guarded repair pipeline.'); echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'; wp_nonce_field('wp_fixpilot_save_ai_settings'); echo '<input type="hidden" name="action" value="wp_fixpilot_save_ai_settings"><p><label><input type="checkbox" name="ai_enabled" value="1" '.checked(1,$cfg['enabled'],false).'> Enable AI Repair</label></p><p>Endpoint <input class="regular-text" name="ai_endpoint" value="'.esc_attr($cfg['endpoint']).'"></p><p>Model <input class="regular-text" name="ai_model" value="'.esc_attr($cfg['model']).'"></p><p>API key <input class="regular-text" type="password" name="ai_api_key" value=""></p>'; submit_button('Save AI Settings'); echo '</form>'; $this->json(get_option('wp_fixpilot_ai_proposal',array())); $this->end(); }
    public function scan(){ $this->auth('wp_fixpilot_scan'); update_option('wp_fixpilot_last_scan',WP_FixPilot_Scanner::run_full_scan(),false); $this->go('wp-fixpilot','Full scan completed.'); }
    public function benchmark(){ $this->auth('wp_fixpilot_benchmark'); update_option('wp_fixpilot_last_benchmark',WP_FixPilot_Benchmark::run(),false); $this->go('wp-fixpilot-performance','Benchmark completed.'); }
    public function clear_log(){ $this->auth('wp_fixpilot_clear_log'); WP_FixPilot_Error_Monitor::clear(); $this->go('wp-fixpilot-issues','Issue log cleared.'); }
    public function save_settings(){ $this->auth('wp_fixpilot_save_settings'); $s=array('monitor_errors'=>isset($_POST['monitor_errors'])?1:0,'weekly_scan'=>isset($_POST['weekly_scan'])?1:0,'auto_expired_cleanup'=>isset($_POST['auto_expired_cleanup'])?1:0,'allow_code_repairs'=>isset($_POST['allow_code_repairs'])?1:0,'backup_retention'=>max(7,min(180,absint($_POST['backup_retention']??30))),'auto_repair_max_steps'=>max(1,min(25,absint($_POST['auto_repair_max_steps']??8)))); update_option('wp_fixpilot_settings',$s,false); WP_FixPilot::sync_schedule(!empty($s['weekly_scan'])); $this->go('wp-fixpilot-settings','Settings saved.'); }
    public function fix(){ $this->auth('wp_fixpilot_fix'); $f=sanitize_key(wp_unslash($_POST['fix']??'')); $r=WP_FixPilot_Fixer::run_named_fix($f); $this->go('wp-fixpilot-repairs',is_wp_error($r)?$r->get_error_message():'Repair completed.'); }
    public function repair_issue(){ $this->auth('wp_fixpilot_repair_issue'); $r=WP_FixPilot_Repair_Engine::repair_issue_by_id(absint($_POST['issue_id']??0)); $this->go('wp-fixpilot-repairs',is_wp_error($r)?$r->get_error_message():'Code repair completed.'); }
    public function safe_repair_all(){ $this->auth('wp_fixpilot_safe_repair_all'); $r=WP_FixPilot_Repair_Center::safe_batch(); $this->go('wp-fixpilot-repairs','Safe Repair All executed '.count($r).' candidate(s).'); }
    public function auto_repair(){ $this->auth('wp_fixpilot_auto_repair'); $s=get_option('wp_fixpilot_settings',array()); $r=WP_FixPilot_Auto_Repair_Workflow::run(absint($s['auto_repair_max_steps']??8)); $this->go('wp-fixpilot-auto-repair',is_wp_error($r)?$r->get_error_message():'Auto Repair finished: '.($r['status']??'unknown')); }
    public function repair_autoload(){ $this->auth('wp_fixpilot_repair_autoload'); $r=WP_FixPilot_Fixer::disable_autoload_for_option(sanitize_text_field(wp_unslash($_POST['option_name']??''))); $this->go('wp-fixpilot-repairs',is_wp_error($r)?$r->get_error_message():'Autoload policy updated.'); }
    public function restore_autoload(){ $this->auth('wp_fixpilot_restore_autoload'); $r=WP_FixPilot_Fixer::restore_autoload_repair(sanitize_text_field(wp_unslash($_POST['repair_id']??''))); $this->go('wp-fixpilot-repairs',is_wp_error($r)?$r->get_error_message():'Autoload policy restored.'); }
    public function restore_config(){ $this->auth('wp_fixpilot_restore_config'); $r=WP_FixPilot_Config::restore_change(sanitize_text_field(wp_unslash($_POST['id']??''))); $this->go('wp-fixpilot-repairs',is_wp_error($r)?$r->get_error_message():'Configuration restored.'); }
    public function safe_mode_start(){ $this->auth('wp_fixpilot_safe_mode_start'); $r=WP_FixPilot_Safe_Mode::start(array()); $this->go('wp-fixpilot-plugins',is_wp_error($r)?$r->get_error_message():'Safe Mode enabled for this browser.'); }
    public function safe_mode_stop(){ $this->auth('wp_fixpilot_safe_mode_stop'); WP_FixPilot_Safe_Mode::stop(); $this->go('wp-fixpilot-plugins','Safe Mode disabled.'); }
    public function conflict_profile(){ $this->auth('wp_fixpilot_conflict_profile'); $r=WP_FixPilot_Conflict_Profiler::run(); $this->go('wp-fixpilot-plugins',is_wp_error($r)?$r->get_error_message():'Conflict Profiler completed.'); }
    public function request_profile(){ $this->auth('wp_fixpilot_request_profile'); $before=get_option('wp_fixpilot_request_profiles',array()); $after=WP_FixPilot_Request_Profiler::run_suite(); update_option('wp_fixpilot_request_profiles',$after,false); if($before) update_option('wp_fixpilot_profile_comparison',WP_FixPilot_Profile_Comparison::compare($before,$after),false); $this->go('wp-fixpilot-profiler','Request Profiler completed.'); }
    public function restore_backup(){ $this->auth('wp_fixpilot_restore_backup'); $r=WP_FixPilot_Backup::restore_by_id(sanitize_text_field(wp_unslash($_POST['id']??''))); $this->go('wp-fixpilot-repairs',is_wp_error($r)?$r->get_error_message():'Backup restored.'); }
    public function update_guard_compare(){ $this->auth('wp_fixpilot_update_guard_compare'); $r=WP_FixPilot_Update_Guard::compare_pending(); $this->go('wp-fixpilot-plugins',is_wp_error($r)?$r->get_error_message():'Update Guard comparison completed.'); }
    public function install_recovery_bridge(){ $this->auth('wp_fixpilot_install_recovery_bridge'); $r=WP_FixPilot_Safety::install_recovery_bridge(); $this->go('wp-fixpilot-safety',is_wp_error($r)?$r->get_error_message():'Emergency recovery bridge installed.'); }
    public function quarantine_plugin(){ $this->auth('wp_fixpilot_quarantine_plugin'); $r=WP_FixPilot_Conflict_Resolution::quarantine(sanitize_text_field(wp_unslash($_POST['plugin']??''))); $this->go('wp-fixpilot-conflicts',is_wp_error($r)?$r->get_error_message():'Plugin quarantined.'); }
    public function restore_quarantined_plugin(){ $this->auth('wp_fixpilot_restore_quarantined_plugin'); $r=WP_FixPilot_Conflict_Resolution::restore(sanitize_text_field(wp_unslash($_POST['plugin']??''))); $this->go('wp-fixpilot-conflicts',is_wp_error($r)?$r->get_error_message():'Plugin restored.'); }
    public function rollback_update(){ $this->auth('wp_fixpilot_rollback_update'); $r=WP_FixPilot_Update_Guard_Pro::rollback(sanitize_text_field(wp_unslash($_POST['id']??''))); $this->go('wp-fixpilot-update-guard-pro',is_wp_error($r)?$r->get_error_message():'Update rollback completed.'); }
    public function save_ai_settings(){ $this->auth('wp_fixpilot_save_ai_settings'); $old=WP_FixPilot_AI_Repair::settings(); $s=array('enabled'=>isset($_POST['ai_enabled'])?1:0,'endpoint'=>esc_url_raw(wp_unslash($_POST['ai_endpoint']??$old['endpoint'])),'model'=>sanitize_text_field(wp_unslash($_POST['ai_model']??$old['model'])),'api_key'=>!empty($_POST['ai_api_key'])?sanitize_text_field(wp_unslash($_POST['ai_api_key'])):$old['api_key'],'max_context_lines'=>120); update_option('wp_fixpilot_ai_settings',$s,false); $this->go('wp-fixpilot-ai','AI settings saved.'); }
    public function ai_propose(){ $this->auth('wp_fixpilot_ai_propose'); $r=WP_FixPilot_AI_Repair::propose(absint($_POST['issue_id']??0)); $this->go('wp-fixpilot-ai',is_wp_error($r)?$r->get_error_message():'AI proposal generated.'); }
    public function ai_apply(){ $this->auth('wp_fixpilot_ai_apply'); $r=WP_FixPilot_AI_Repair::apply_saved(); $this->go('wp-fixpilot-ai',is_wp_error($r)?$r->get_error_message():'AI proposal applied.'); }
    public function export(){ $this->auth('wp_fixpilot_export'); $r=$this->report(); $r['benchmark']=get_option('wp_fixpilot_last_benchmark',array()); $r['request_profiles']=get_option('wp_fixpilot_request_profiles',array()); $r['repairs']=get_option('wp_fixpilot_repair_log',array()); nocache_headers(); header('Content-Type: application/json; charset=utf-8'); header('Content-Disposition: attachment; filename=wp-fixpilot-report-'.gmdate('Y-m-d-His').'.json'); echo wp_json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES); exit; }
}
