<?php
if(!defined('ABSPATH'))exit;
class WP_FixPilot_Conflict_Resolution {
 public static function init(){add_action('admin_init',array(__CLASS__,'enforce_quarantine'));}
 public static function plans(){ $profile=(array)get_option('wp_fixpilot_conflict_profile',array());$scan=(array)get_option('wp_fixpilot_last_scan',array());$plugins=isset($scan['plugins'])?$scan['plugins']:array();$out=array();foreach($plugins as $p){$file=isset($p['file'])?$p['file']:'';$slug=dirname($file);if('.'===$slug)$slug=basename($file,'.php');$row=array('plugin'=>$file,'name'=>isset($p['name'])?$p['name']:$file,'risk'=>isset($p['risk'])?(int)$p['risk']:0,'recommendation'=>isset($p['recommendation'])?$p['recommendation']:'review','confirmed'=>false,'evidence'=>array());foreach($profile as $pr){if(isset($pr['plugin'])&&$pr['plugin']===$file){$delta=isset($pr['delta_ms'])?(float)$pr['delta_ms']:0;if($delta>300){$row['confirmed']=true;$row['evidence'][]='Loopback improved by '.round($delta).' ms when excluded.';}}}$out[]=$row;}usort($out,function($a,$b){return ($b['confirmed']<=>$a['confirmed'])?:($b['risk']<=>$a['risk']);});return $out; }
 public static function quarantine($plugin){require_once ABSPATH.'wp-admin/includes/plugin.php';$plugin=plugin_basename($plugin);if(!is_plugin_active($plugin))return new WP_Error('fixpilot_not_active','Plugin is not active.');$record=(array)get_option('wp_fixpilot_quarantine',array());$record[$plugin]=array('time'=>time(),'version'=>isset(get_plugins()[$plugin]['Version'])?get_plugins()[$plugin]['Version']:'');update_option('wp_fixpilot_quarantine',$record,false);deactivate_plugins($plugin,true,is_multisite());return true;}
 public static function restore($plugin){require_once ABSPATH.'wp-admin/includes/plugin.php';$plugin=plugin_basename($plugin);$r=activate_plugin($plugin,'',is_multisite(),true);if(is_wp_error($r))return $r;$q=(array)get_option('wp_fixpilot_quarantine',array());unset($q[$plugin]);update_option('wp_fixpilot_quarantine',$q,false);return true;}
 public static function enforce_quarantine(){/* Record-only safeguard: quarantine is performed through WordPress deactivate_plugins(), never by filtering active_plugins on every request. */}
 public static function quarantined(){return (array)get_option('wp_fixpilot_quarantine',array());}
}
