<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class WP_FixPilot {
	private static $instance=null;
	public static function instance(){if(null===self::$instance)self::$instance=new self();return self::$instance;}
	private function __construct(){require_once WP_FIXPILOT_DIR.'includes/class-wp-fixpilot-config.php';WP_FixPilot_Config::bootstrap();require_once WP_FIXPILOT_DIR.'includes/class-wp-fixpilot-runtime-attribution.php';require_once WP_FIXPILOT_DIR.'includes/class-wp-fixpilot-hook-profiler.php';require_once WP_FIXPILOT_DIR.'includes/class-wp-fixpilot-request-profiler.php';WP_FixPilot_Request_Profiler::bootstrap();foreach(array('scanner','error-monitor','plugin-analyzer','performance','fixer','database','backup','repair-engine','benchmark','woocommerce','safe-mode','conflict-profiler','update-guard','optimization-plan','woocommerce-bottleneck','profile-comparison','recommendation-engine','plugin-repair-plan','callback-analyzer','action-center','repair-center','auto-repair-workflow','admin','safety','repair-rule-library','performance-repair','conflict-resolution','update-guard-pro','ai-repair','release-readiness') as $name){require_once WP_FIXPILOT_DIR.'includes/class-wp-fixpilot-'.$name.'.php';} add_action('plugins_loaded',array($this,'init')); add_filter('cron_schedules',array($this,'cron_schedules')); add_action('wp_fixpilot_weekly_scan',array($this,'scheduled_scan'));}
	public function init(){WP_FixPilot_Safety::init();WP_FixPilot_Conflict_Resolution::init();add_action('wp_ajax_wp_fixpilot_probe',array($this,'ajax_probe'));add_action('wp_ajax_nopriv_wp_fixpilot_probe',array($this,'ajax_probe'));load_plugin_textdomain('wp-fixpilot',false,dirname(plugin_basename(WP_FIXPILOT_FILE)).'/languages');WP_FixPilot_Error_Monitor::instance()->init();WP_FixPilot_Update_Guard::init();WP_FixPilot_Update_Guard_Pro::init();if(is_admin())WP_FixPilot_Admin::instance()->init();$this->declare_woocommerce_compatibility();}
	public function ajax_probe(){if(!WP_FixPilot_Request_Profiler::is_active()){status_header(403);wp_die('Forbidden');}wp_send_json_success(array('probe'=>'ok','time'=>microtime(true)));}
	public function declare_woocommerce_compatibility(){if(class_exists('\\Automattic\\WooCommerce\\Utilities\\FeaturesUtil')){\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility('custom_order_tables',WP_FIXPILOT_FILE,true);\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility('cart_checkout_blocks',WP_FIXPILOT_FILE,true);}}
	public function cron_schedules($s){if(!isset($s['weekly']))$s['weekly']=array('interval'=>WEEK_IN_SECONDS,'display'=>__('Once Weekly','wp-fixpilot'));return $s;}
	public function scheduled_scan(){ $settings=get_option('wp_fixpilot_settings',array()); if(empty($settings['weekly_scan']))return; if(!empty($settings['auto_expired_cleanup']))WP_FixPilot_Fixer::cleanup_expired_transients(); WP_FixPilot_Backup::cleanup_old(isset($settings['backup_retention'])?$settings['backup_retention']:30); update_option('wp_fixpilot_last_scan',WP_FixPilot_Scanner::run_full_scan(),false); }
	public static function sync_schedule($enabled){$ts=wp_next_scheduled('wp_fixpilot_weekly_scan');if($enabled&&!$ts)wp_schedule_event(time()+HOUR_IN_SECONDS,'weekly','wp_fixpilot_weekly_scan');elseif(!$enabled&&$ts)wp_clear_scheduled_hook('wp_fixpilot_weekly_scan');}
	public static function activate(){require_once WP_FIXPILOT_DIR.'includes/class-wp-fixpilot-error-monitor.php';WP_FixPilot_Error_Monitor::install_table();self::sync_schedule(true);add_option('wp_fixpilot_settings',array('monitor_errors'=>1,'weekly_scan'=>1,'auto_expired_cleanup'=>0,'allow_code_repairs'=>0,'backup_retention'=>30,'auto_repair_max_steps'=>8),'',false);add_option('wp_fixpilot_runtime_config',array('production_hide_errors'=>0,'heartbeat_interval'=>0,'wc_session_fallback'=>0),'',false);}
	public static function deactivate(){WP_FixPilot_Safety::deactivate_cleanup();wp_clear_scheduled_hook('wp_fixpilot_weekly_scan');wp_clear_scheduled_hook('wp_fixpilot_daily_wc_session_cleanup');}
}
