<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class WP_FixPilot_Optimization_Plan {
	public static function build( $scan, $profiles=array() ) {
		$items=array(); $perf=isset($scan['performance'])?$scan['performance']:array(); $woo=isset($scan['woocommerce'])?$scan['woocommerce']:array();
		if(!empty($perf['autoload_bytes']) && $perf['autoload_bytes']>2*MB_IN_BYTES)self::add($items,95,'Reduce autoloaded options','Database','High','Every uncached PHP request loads more than 2 MB of options.','Review TOP autoload rows; disable autoload only after ownership is identified.');
		if(!empty($perf['overdue_cron_events']) && $perf['overdue_cron_events']>10)self::add($items,88,'Repair delayed WP-Cron','Background jobs','High','There are overdue cron events.','Inspect failing hooks and consider real server cron for production stores.');
		if(empty($perf['object_cache']) && !empty($woo['active']))self::add($items,62,'Add persistent object cache','Cache','Medium','WooCommerce is active and no persistent object cache is detected.','Use Redis/Memcached only when supported by the host and validate checkout afterwards.');
		if(!empty($woo['scheduled_actions']['failed']))self::add($items,92,'Resolve failed Action Scheduler jobs','WooCommerce','High',$woo['scheduled_actions']['failed'].' failed jobs detected.','Identify failing hooks before deleting anything; fix the responsible extension first.');
		if(!empty($woo['scheduled_actions']['pending']) && $woo['scheduled_actions']['pending']>1000)self::add($items,86,'Reduce Action Scheduler backlog','WooCommerce','High','More than 1,000 pending jobs are queued.','Inspect oldest pending groups/hooks and worker cadence.');
		if(!empty($profiles['targets']) && is_array($profiles['targets'])){foreach($profiles['targets'] as $name=>$p){if(!is_array($p)||isset($p['error']))continue;$total=isset($p['total_ms'])?(float)$p['total_ms']:0;$sql=isset($p['sql_ms'])?(float)$p['sql_ms']:0;$qc=isset($p['query_count'])?(int)$p['query_count']:0;if($total>1500)self::add($items,90,'Reduce slow request: '.$name,'Request profile','High','Server execution is '.round($total).' ms.','Use the slow SQL/repeated query table below to identify the responsible component.');if($sql>500)self::add($items,89,'Reduce SQL time: '.$name,'Database','High','SQL consumed '.round($sql).' ms across '.$qc.' queries.','Fix slow/repeated queries before adding cache layers.');elseif($qc>150)self::add($items,72,'Reduce query count: '.$name,'Database','Medium',$qc.' SQL queries were executed.','Review repeated patterns for N+1 behavior.');if(!empty($p['http_count']) && $p['http_count']>3)self::add($items,70,'Review outbound HTTP: '.$name,'External calls','Medium',$p['http_count'].' outbound HTTP calls occurred in one request.','Remove synchronous third-party calls from page generation where possible.');}}
		if(class_exists('WP_FixPilot_Runtime_Attribution')){$attr=WP_FixPilot_Runtime_Attribution::aggregate($profiles);if(!empty($attr[0])&&$attr[0]['score']>=35){$x=$attr[0];self::add($items,min(94,60+(int)round($x['score']/3)),'Reduce runtime cost: '.$x['label'],'Component attribution',$x['score']>=70?'High':'Medium','FixPilot attributed '.$x['total_ms'].' ms of slow SQL/outbound HTTP to this '.$x['type'].'.','Inspect its attributed SQL/HTTP rows, then update, reconfigure, replace or patch the responsible component.');}}
		if(class_exists('WP_FixPilot_WooCommerce_Bottleneck')&&!empty($woo['active'])){$wb=WP_FixPilot_WooCommerce_Bottleneck::analyze($profiles);if(!empty($wb['top_variable_products'][0])&&$wb['top_variable_products'][0]['variation_count']>200){$v=$wb['top_variable_products'][0];self::add($items,78,'Review variation hotspot #'.$v['product_id'],'WooCommerce catalog','Medium',$v['variation_count'].' variations are attached to '.$v['title'].'.','Profile that product page and reduce unnecessary variation combinations or heavy variation extensions.');}}
		usort($items,function($a,$b){return $b['score']<=>$a['score'];}); return array_slice($items,0,20);
	}
	private static function add(&$items,$score,$title,$area,$impact,$why,$action){$items[]=array('score'=>$score,'title'=>$title,'area'=>$area,'impact'=>$impact,'why'=>$why,'action'=>$action);}
}
