<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class WP_FixPilot_Safety {
 const LOCK='wp_fixpilot_repair_lock'; const LOCK_TTL=900;
 public static function init(){add_action('wp_fixpilot_safety_watchdog',array(__CLASS__,'watchdog'));if(!wp_next_scheduled('wp_fixpilot_safety_watchdog'))wp_schedule_event(time()+300,'hourly','wp_fixpilot_safety_watchdog');}
 public static function acquire_lock($context='repair'){self::watchdog();$payload=array('token'=>wp_generate_uuid4(),'context'=>sanitize_key($context),'time'=>time(),'user'=>get_current_user_id());if(!add_option(self::LOCK,$payload,'','no'))return new WP_Error('fixpilot_locked',__('Another FixPilot repair is already running.','wp-fixpilot'));return $payload['token'];}
 public static function release_lock($token=''){ $cur=get_option(self::LOCK,array());if(!$token||empty($cur['token'])||hash_equals((string)$cur['token'],(string)$token))delete_option(self::LOCK); }
 public static function watchdog(){ $cur=get_option(self::LOCK,array());if(!empty($cur['time']) && time()-(int)$cur['time']>self::LOCK_TTL)delete_option(self::LOCK); }
 public static function environment(){return function_exists('wp_get_environment_type')?wp_get_environment_type():'production';}
 public static function preflight($needs_write=false,$estimated_bytes=1048576){$issues=array();$env=self::environment();if(is_multisite()&&!is_network_admin())$issues[]='multisite-site-admin';if($needs_write&&!is_writable(WP_CONTENT_DIR))$issues[]='wp-content-not-writable';$free=@disk_free_space(WP_CONTENT_DIR);if(false!==$free && $free<max(20*1024*1024,$estimated_bytes*3))$issues[]='low-disk-space';$upload=wp_upload_dir();if(!empty($upload['error']))$issues[]='uploads-unavailable';return array('ok'=>empty($issues),'environment'=>$env,'multisite'=>is_multisite(),'disk_free'=>$free,'issues'=>$issues,'self_protection'=>true,'recovery_bridge'=>self::bridge_status());}
 public static function can_edit_file($file){$file=wp_normalize_path($file);if(0===strpos($file,wp_normalize_path(WP_FIXPILOT_DIR)))return new WP_Error('fixpilot_self_protected',__('FixPilot never repairs its own source files.','wp-fixpilot'));if(is_multisite()&&!is_network_admin())return new WP_Error('fixpilot_multisite_scope',__('File repair on multisite requires Network Admin.','wp-fixpilot'));return true;}
 public static function install_recovery_bridge(){if(!defined('WPMU_PLUGIN_DIR'))return new WP_Error('fixpilot_no_mu',__('MU-plugin directory is unavailable.','wp-fixpilot'));if(!is_dir(WPMU_PLUGIN_DIR)&&!wp_mkdir_p(WPMU_PLUGIN_DIR))return new WP_Error('fixpilot_mu_mkdir',__('Could not create mu-plugins directory.','wp-fixpilot'));$file=trailingslashit(WPMU_PLUGIN_DIR).'wp-fixpilot-recovery.php';$code="<?php\n/* Plugin Name: WP FixPilot Emergency Recovery */\nif(!defined('ABSPATH'))exit;\n\$m=WP_CONTENT_DIR.'/fixpilot-recovery.json';\nif(is_file(\$m)){\$d=json_decode((string)@file_get_contents(\$m),true);\$trigger=defined('WP_FIXPILOT_EMERGENCY_RECOVER')&&WP_FIXPILOT_EMERGENCY_RECOVER;if(!\$trigger&&!empty(\$_GET['wp_fixpilot_recover'])&&!empty(\$d['token']))\$trigger=hash_equals((string)\$d['token'],(string)\$_GET['wp_fixpilot_recover']);if(\$trigger&&is_array(\$d)&&!empty(\$d['armed'])&&!empty(\$d['target'])&&!empty(\$d['backup'])){\$t=wp_normalize_path(\$d['target']);\$b=wp_normalize_path(\$d['backup']);\$roots=array(wp_normalize_path(WP_PLUGIN_DIR).'/',wp_normalize_path(get_theme_root()).'/');\$ok=false;foreach(\$roots as \$r){if(strpos(\$t,\$r)===0)\$ok=true;}if(\$ok&&is_file(\$b)&&time()-(int)\$d['time']<DAY_IN_SECONDS){@copy(\$b,\$t);\$d['armed']=false;@file_put_contents(\$m,json_encode(\$d),LOCK_EX);}}}\n";if(false===@file_put_contents($file,$code,LOCK_EX))return new WP_Error('fixpilot_mu_write',__('Could not install emergency recovery bridge.','wp-fixpilot'));return true;}
 public static function bridge_status(){return defined('WPMU_PLUGIN_DIR')&&is_file(trailingslashit(WPMU_PLUGIN_DIR).'wp-fixpilot-recovery.php');}
 public static function arm_file_recovery($target,$backup){$r=self::can_edit_file($target);if(is_wp_error($r))return $r;if(!self::bridge_status()){ $i=self::install_recovery_bridge(); if(is_wp_error($i))return $i; }$manifest=WP_CONTENT_DIR.'/fixpilot-recovery.json';$data=array('armed'=>true,'time'=>time(),'token'=>wp_generate_password(32,false,false),'target'=>wp_normalize_path($target),'backup'=>wp_normalize_path($backup));return false!==@file_put_contents($manifest,wp_json_encode($data),LOCK_EX);}
 public static function disarm_file_recovery(){ $m=WP_CONTENT_DIR.'/fixpilot-recovery.json';if(is_file($m)){ $d=json_decode((string)@file_get_contents($m),true);if(!is_array($d))$d=array();$d['armed']=false;@file_put_contents($m,wp_json_encode($d),LOCK_EX);} }
 public static function deactivate_cleanup(){wp_clear_scheduled_hook('wp_fixpilot_safety_watchdog');delete_option(self::LOCK);self::disarm_file_recovery();}
}
